handlers = list()

from handler import activity
from handler import master
from handler import token
from handler import user
from handler import userinfo
from handler import qiniu
from handler import notice
from handler import event
from handler import index
from handler import order
from handler import wxpay
from handler import yunpian
from handler import post
from handler import supervise
from handler import circle
from handler import mode
from handler import appointment
from handler import comment
from handler import category
from handler import vcoin
from handler import tip
from handler.superside import label
from handler.superside import mode
from handler.superside import application
from handler.superside import master
from handler.superside import user 
from handler.superside import event
from handler.superside import index
from handler.superside import order
from handler.superside import category
from handler.superside import iconfig
from handler.superside import circle
from handler.superside import userteam
